Cecilia Barnsby, Bhavya Devarsu, Michelle Li, Rhiannon Staley, Jarmarr Washington 

1. Load Data 
```{r}
# Import libraries
set.seed(2)
library(ggplot2)
library(tidyverse)

train_values <- read.csv("train_values.csv")
train_labels <- read.csv("train_labels.csv")

# Merge values and labels by building_id
buildings <- merge(train_values, train_labels, by = "building_id")

# Check dimensions
dim(buildings)

# Check for missing values
colSums(is.na(buildings))

# Change categorical values to factors
categorical <- c(
  "geo_level_1_id",
  "geo_level_2_id",
  "geo_level_3_id",
  "land_surface_condition",
  "foundation_type",
  "roof_type",
  "ground_floor_type",
  "other_floor_type",
  "position",
  "plan_configuration",
  "legal_ownership_status",
  "damage_grade"
)

buildings[categorical] <- lapply(
  buildings[categorical],
  as.factor
)

summary(buildings)

# Distribution of response variable
ggplot(buildings, aes(x = damage_grade)) +
  geom_bar() +
  labs(
    x = "Damage Grade",
    y = "Count",
    title = "Distribution of Damage Grade"
  )
```

2. Numeric Features

```{r}
numeric_features <- c(
  "count_floors_pre_eq",
  "age",
  "area_percentage",
  "height_percentage",
  "count_families"
)

plots <- purrr::map(numeric_features, function(feature) {
  ggplot(buildings, aes(
    x = .data[[feature]],
    y = damage_grade
  )) +
    geom_jitter(alpha = 0.3, height = 0.1) +
    labs(
      x = feature,
      y = "Damage grade",
      title = paste("Damage grade vs", feature)
    )
})

plots
```

### Inspect age
```{r}

table(buildings$age[buildings$age > 200])

table(
  extreme_age = buildings$age > 200,
  damage_grade = buildings$damage_grade
)

# Filter buildings with age 995
age_995 <- buildings[buildings$age == 995, ]


age_995_sample <- age_995[
  sample(nrow(age_995), 30),
  c(
    "age",
    "damage_grade",
    "geo_level_1_id",
    "count_floors_pre_eq",
    "area_percentage",
    "height_percentage",
    "foundation_type",
    "roof_type",
    "ground_floor_type",
    "other_floor_type"
  )
]

age_995_sample
```


3. Categorical Variables

```{r}
categorical_features <- c(
  "land_surface_condition",
  "foundation_type",
  "roof_type",
  "ground_floor_type",
  "other_floor_type",
  "position",
  "plan_configuration",
  "legal_ownership_status"
)

plots <- purrr::map(categorical_features, function(feature) {

  ggplot(buildings, aes(
    x = .data[[feature]],
    fill = factor(damage_grade)
  )) +
    geom_bar(position = "fill") +
    labs(
      x = feature,
      y = "Proportion",
      fill = "Damage grade",
      title = paste("Damage grade vs", feature)
    ) +
    coord_flip()

})

plots
```